name: test
run-name: pull-main
on: 
    push:
        branches:
            - main
jobs:
    pull-main:
        runs-on: ubuntu-latest
        
        steps:
          - name: Pull main branch
            uses: actions/checkout@v2  
            with:
                ref: main